### ISSUE TITLE
fontTex is not defined

### ISSUE THREAD

**Issue by Harrison-Miller** [Mischa-Alff/imgui-backends#1]
in imgui-rendering-SFML
line 27-28
vtx_buffer[i].texCoords.x_=ImImpl::ImImpl_fontTex.getSize().x;
vtx_buffer[i].texCoords.y_=ImImpl::ImImpl_fontTex.getSize().y;

fontTex is not defined as it was removed in the last commit.

**Comment by Mischa-Alff** [comment]
Sorry for leaving this issue open for so long without responding nor fixing. This is fixed in the upcoming commit. Thanks for the bug report.
