### ISSUE TITLE
Build errors after closing issue #3

### ISSUE THREAD

**Issue by vrkgtpwmvz** [Mischa-Alff/imgui-backends#5]
Thanks for your attention.

I have tried the new rendering but now it gives a bunch of errors while compiling like:
LNK2019 unresolved external symbol __imp__glBindTexture@8 referenced in function "void __cdecl ImGui::ImImpl::ImImpl_RenderDrawLists(struct ImDrawData *)" (?ImImpl_RenderDrawLists@ImImpl@ImGui@@YAXPAUImDrawData@@@Z)

I'm using your example code. Did something change in the setup? I didn't had any problems running the old one in the old imgui version.

**Comment by Mischa-Alff** [comment]
Hi, you need to link to OpenGL.
The SFML backend now uses OpenGL due to SFML's `sf::VertexArray` not supporting indices.

**Comment by vrkgtpwmvz** [comment]
Got it working, thanks man!
