### ISSUE TITLE
Having a static sf::Texture throws exception when static linking SFML

### ISSUE THREAD

**Issue by vrkgtpwmvz** [Mischa-Alff/imgui-backends#6]
I am pre-emptively opening this issue when I have not looked much into it. I'll try see what I can do about it but as I say here: http://en.sfml-dev.org/forums/index.php?topic=19226.0 I don't know if I have the know how-to fix the issue. I'll comment back if I have any luck with it.

**Comment by Mischa-Alff** [comment]
This will be fixed in the next push.
